channels:
  - rusty1s
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Minimal dependencies for the competition
  - python=3.7
  - scip=7.0.3
  - ecole=0.7.3
  - numpy
  - pyscipopt

  # additional conda dependencies go here
  - pytorch=1.9.0
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pytorch-geometric=1.7.2